# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chaertli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaertli',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 4, 20, 17, 7, 49, 329404, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
