# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chaertli', '0002_chaertli_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loesig', models.BooleanField(default=False)),
                ('chaertli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaertli.Chaertli')),
            ],
        ),
    ]
