# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chaertli', '0003_sitae'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInhaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhaut', models.TextField()),
                ('sitae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaertli.Sitae')),
            ],
        ),
    ]
